namespace ImpulseVibrations
{
	/// <summary>
	/// A concrete UIFeedbackGenerator subclass that creates haptics to communicate successes, failures, and warnings.
	/// iOS 10+
	/// https://developer.apple.com/documentation/uikit/uinotificationfeedbackgenerator
	/// </summary>
	public enum NotificationTypeFeedback
	{
		/// <summary>
		/// The type of notification generated by a UINotificationFeedbackGenerator object. A notification feedback type, indicating that a task has completed successfully.
		/// iOS 10+
		/// https://developer.apple.com/documentation/uikit/uinotificationfeedbackgenerator/feedbacktype
		/// </summary>
		NOTIFICATION_SUCCESS = 0,
		/// <summary>
		/// The type of notification generated by a UINotificationFeedbackGenerator object. A notification feedback type, indicating that a task has produced a warning.
		/// iOS 10+
		/// https://developer.apple.com/documentation/uikit/uinotificationfeedbackgenerator/feedbacktype
		/// </summary>
		NOTIFICATION_WARNING = 1,
		/// <summary>
		/// The type of notification generated by a UINotificationFeedbackGenerator object. A notification feedback type, indicating that a task has failed.
		/// iOS 10+
		/// https://developer.apple.com/documentation/uikit/uinotificationfeedbackgenerator/feedbacktype
		/// </summary>
		NOTIFICATION_ERROR = 2
	}
}